/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import java.sql.Connection;
import util.ConnectionFactory;
import view.MainScreeen;

public class App {
   

    public static void main(String[] args) {
      
        Connection c = ConnectionFactory.getConnection();
        
        ConnectionFactory.closeConnection(c);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreeen().setVisible(true);
            }
        });        
        
    }
    
   
}
